-- =============================================================================
-- P1-090: Projects production schema alignment
-- Fixes FND-PROJ-001 (schema mismatch), FND-PROJ-003 (closure override path),
-- and supports FND-PROJ-004 (full ProjectForm fields).
-- Also keeps the live Projects API compatible with the existing legacy rows.
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- 1. Add the fields used by the Projects API/specification.
-- -----------------------------------------------------------------------------
ALTER TABLE public.projects
  ADD COLUMN IF NOT EXISTS project_code text,
  ADD COLUMN IF NOT EXISTS client_id uuid,
  ADD COLUMN IF NOT EXISTS manager_id uuid,
  ADD COLUMN IF NOT EXISTS platform text,
  ADD COLUMN IF NOT EXISTS contract_value numeric(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS currency text NOT NULL DEFAULT 'PKR',
  ADD COLUMN IF NOT EXISTS budget_amount numeric(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS department text,
  ADD COLUMN IF NOT EXISTS cost_center text,
  ADD COLUMN IF NOT EXISTS is_confidential boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS created_by uuid,
  ADD COLUMN IF NOT EXISTS closure_reason text,
  ADD COLUMN IF NOT EXISTS closed_by uuid,
  ADD COLUMN IF NOT EXISTS closed_at timestamptz;

-- Existing legacy rows use Active/Completed/On Hold. Convert them to the
-- canonical API vocabulary before replacing the CHECK constraint.
UPDATE public.projects SET status = 'ACTIVE' WHERE upper(status) = 'ACTIVE';
UPDATE public.projects SET status = 'CLOSED' WHERE upper(status) IN ('COMPLETED', 'CLOSED');
UPDATE public.projects SET status = 'ON_HOLD' WHERE upper(status) IN ('ON HOLD', 'ON_HOLD');
UPDATE public.projects SET status = 'CANCELLED' WHERE upper(status) = 'CANCELLED';

-- Preserve historical user ownership as created_by when available.
UPDATE public.projects
SET created_by = user_id
WHERE created_by IS NULL;

UPDATE public.projects
SET is_active = CASE WHEN status IN ('CLOSED', 'CANCELLED') OR deleted_at IS NOT NULL THEN false ELSE true END
WHERE is_active IS DISTINCT FROM CASE WHEN status IN ('CLOSED', 'CANCELLED') OR deleted_at IS NOT NULL THEN false ELSE true END;

-- Generate stable codes for old rows. New rows are generated by finance.get_next_number.
WITH numbered AS (
  SELECT id, 'PRJ-LEGACY-' || substr(md5(id::text), 1, 10) AS generated_code
  FROM public.projects
  WHERE project_code IS NULL OR btrim(project_code) = ''
)
UPDATE public.projects p
SET project_code = n.generated_code
FROM numbered n
WHERE p.id = n.id;

ALTER TABLE public.projects
  ALTER COLUMN project_code SET NOT NULL;

-- Make any pre-existing duplicate codes unique within an organization before
-- installing the canonical unique index.
WITH duplicates AS (
  SELECT id, project_code,
         row_number() OVER (PARTITION BY organization_id, project_code ORDER BY created_at, id) AS rn
  FROM public.projects
)
UPDATE public.projects p
SET project_code = p.project_code || '-DUP-' || d.rn::text
FROM duplicates d
WHERE p.id = d.id AND d.rn > 1;

-- Remove the legacy status CHECK and install the canonical vocabulary.
ALTER TABLE public.projects DROP CONSTRAINT IF EXISTS projects_status_check;
ALTER TABLE public.projects
  ADD CONSTRAINT projects_status_check
  CHECK (status IN ('ACTIVE', 'ON_HOLD', 'CLOSED', 'CANCELLED'));

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.projects'::regclass AND conname = 'projects_contract_value_check') THEN
    ALTER TABLE public.projects ADD CONSTRAINT projects_contract_value_check CHECK (contract_value >= 0);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.projects'::regclass AND conname = 'projects_budget_amount_check') THEN
    ALTER TABLE public.projects ADD CONSTRAINT projects_budget_amount_check CHECK (budget_amount >= 0);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.projects'::regclass AND conname = 'projects_currency_check') THEN
    ALTER TABLE public.projects ADD CONSTRAINT projects_currency_check CHECK (currency ~ '^[A-Z]{3}$');
  END IF;
END $$;

-- -----------------------------------------------------------------------------
-- 2. Relationship constraints. Add only when absent.
-- -----------------------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.projects'::regclass
      AND conname = 'projects_client_id_fkey'
  ) THEN
    ALTER TABLE public.projects
      ADD CONSTRAINT projects_client_id_fkey
      FOREIGN KEY (client_id) REFERENCES public.clients(id) ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.projects'::regclass
      AND conname = 'projects_manager_id_fkey'
  ) THEN
    ALTER TABLE public.projects
      ADD CONSTRAINT projects_manager_id_fkey
      FOREIGN KEY (manager_id) REFERENCES public.profiles(id) ON DELETE SET NULL;
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS projects_org_project_code_uq
  ON public.projects (organization_id, project_code)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_projects_org_client
  ON public.projects (organization_id, client_id);

CREATE INDEX IF NOT EXISTS idx_projects_org_manager
  ON public.projects (organization_id, manager_id);

-- -----------------------------------------------------------------------------
-- 3. Fix the profitability view (FND-PROJ-002).
--    The old view CROSS JOINed every project to every organization. This version
--    is organization-scoped and keeps one row per project.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW reporting.v_project_profitability
WITH (security_invoker = true) AS
WITH project_gl AS (
  SELECT
    p.id AS project_id, p.name AS project_name, p.client_name, p.status AS project_status,
    p.user_id, p.organization_id,
    COALESCE(SUM(CASE WHEN je.status = 'POSTED' AND coa.account_type = 'REVENUE'
      THEN jl.base_credit - jl.base_debit ELSE 0 END), 0) AS revenue,
    COALESCE(SUM(CASE WHEN je.status = 'POSTED' AND coa.account_type IN ('COST_OF_SALES','OPERATING_EXPENSE')
      THEN jl.base_debit - jl.base_credit ELSE 0 END), 0) AS total_direct_cost,
    COALESCE(SUM(CASE WHEN je.status = 'POSTED' AND coa.account_type IN ('COST_OF_SALES','OPERATING_EXPENSE')
      AND (lower(coalesce(coa.name,'')) LIKE '%platform fee%' OR lower(coalesce(coa.name,'')) LIKE '%platform fees%'
           OR lower(coalesce(coa.report_mapping,'')) LIKE '%platform%fee%')
      THEN jl.base_debit - jl.base_credit ELSE 0 END), 0) AS platform_fees,
    COALESCE(SUM(CASE WHEN je.status = 'POSTED' AND coa.account_type IN ('COST_OF_SALES','OPERATING_EXPENSE')
      AND (lower(coalesce(coa.name,'')) LIKE '%contractor%' OR lower(coalesce(coa.report_mapping,'')) LIKE '%contractor%')
      THEN jl.base_debit - jl.base_credit ELSE 0 END), 0) AS contractor_cost,
    COALESCE(SUM(CASE WHEN je.status = 'POSTED' AND coa.account_type IN ('COST_OF_SALES','OPERATING_EXPENSE')
      AND (lower(coalesce(coa.name,'')) LIKE '%software%' OR lower(coalesce(coa.name,'')) LIKE '%api cost%'
           OR lower(coalesce(coa.report_mapping,'')) LIKE '%software%' OR lower(coalesce(coa.report_mapping,'')) LIKE '%api%')
      THEN jl.base_debit - jl.base_credit ELSE 0 END), 0) AS software_api_cost,
    COALESCE(SUM(CASE WHEN je.status = 'POSTED'
      AND (je.source_type = 'INVOICE_REFUND' OR lower(coalesce(coa.name,'')) LIKE '%refund%' OR lower(coalesce(coa.name,'')) LIKE '%rework%')
      THEN jl.base_debit - jl.base_credit ELSE 0 END), 0) AS refunds_rework
  FROM public.projects p
  LEFT JOIN finance.journal_entries je ON je.project_id = p.id
  LEFT JOIN finance.journal_lines jl ON jl.journal_entry_id = je.id
  LEFT JOIN finance.chart_of_accounts coa ON coa.id = jl.account_id
  WHERE p.organization_id = core.current_user_org_id()
  GROUP BY p.id, p.name, p.client_name, p.status, p.user_id, p.organization_id
), components AS (
  SELECT pg.*, GREATEST(pg.total_direct_cost - pg.platform_fees - pg.contractor_cost - pg.software_api_cost - pg.refunds_rework, 0) AS other_direct_cost
  FROM project_gl pg
)
SELECT
  c.project_id, c.project_name, c.client_name, c.project_status, c.user_id, c.revenue,
  c.total_direct_cost AS direct_cost,
  c.revenue - c.total_direct_cost AS gross_profit,
  CASE WHEN c.revenue <> 0 THEN round(((c.revenue - c.total_direct_cost) / c.revenue) * 100, 2) ELSE NULL END AS margin_percent,
  c.organization_id, org.base_currency, now() AS data_as_of
FROM components c
JOIN core.organizations org ON org.id = c.organization_id;

ALTER VIEW reporting.v_project_profitability OWNER TO postgres;

COMMENT ON VIEW reporting.v_project_profitability IS
  'Organization-scoped one-row-per-project profitability view. Direct costs are split into platform fees, contractor, software/API, refunds/rework, and other direct costs; gross profit = revenue - total direct cost.';

COMMIT;
